title: Aniket Srinivasan Ashok
description: ML Researcher & Undergraduate Student at the University of Waterloo
url: "https://aniketsrinivasan.github.io"
baseurl: ""

markdown: kramdown
highlighter: rouge
permalink: /writing/:year/:month/:day/:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

